<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CertificateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $certificates = [
            [
                'name' => 'Belajar Fundamental Front-End Web Development',
                'issuing_organization' => 'Dicoding Indonesia',
                'issue_date' => 'Jan 2025',
                'expiration_date' => 'Jan 2028',
                'credential_id' => 'NVP75GN3RXR0',
                'credential_url' => 'https://www.dicoding.com/certificates/NVP75GN3RXR0',
                'sort_order' => 1,
            ],
            [
                'name' => 'Belajar Dasar AI',
                'issuing_organization' => 'Dicoding Indonesia',
                'issue_date' => 'Okt 2024',
                'expiration_date' => 'Okt 2027',
                'credential_id' => 'JLX14270GX72',
                'credential_url' => null,
                'sort_order' => 2,
            ],
            [
                'name' => 'Belajar Dasar Visualisasi Data',
                'issuing_organization' => 'Dicoding Indonesia',
                'issue_date' => 'Okt 2024',
                'expiration_date' => 'Okt 2027',
                'credential_id' => 'JMZV4DDYDXN9',
                'credential_url' => null,
                'sort_order' => 3,
            ],
            [
                'name' => 'Memulai Pemrograman dengan Python',
                'issuing_organization' => 'Dicoding Indonesia',
                'issue_date' => 'Okt 2024',
                'expiration_date' => 'Okt 2027',
                'credential_id' => 'NVP7477MVPR0',
                'credential_url' => null,
                'sort_order' => 4,
            ],
            [
                'name' => 'Belajar Machine Learning untuk Pemula',
                'issuing_organization' => 'Dicoding Indonesia',
                'issue_date' => 'Okt 2024',
                'expiration_date' => 'Okt 2027',
                'credential_id' => 'MRZMYL9MRZYQ',
                'credential_url' => null,
                'sort_order' => 5,
            ],
            [
                'name' => 'Design (Professional Academy)',
                'issuing_organization' => 'Digital Talent Scholarship',
                'issue_date' => 'Jul 2024',
                'expiration_date' => null,
                'credential_id' => '1987880840-365',
                'credential_url' => null,
                'sort_order' => 6,
            ],
            [
                'name' => 'Introduction to Microsoft Excel',
                'issuing_organization' => 'Coursera',
                'issue_date' => 'Jul 2024',
                'expiration_date' => null,
                'credential_id' => 'VMPRR6SHXJFP',
                'credential_url' => null,
                'sort_order' => 7,
            ],
            [
                'name' => 'Desain UX Google Specialization',
                'issuing_organization' => 'Coursera',
                'issue_date' => 'Jul 2024',
                'expiration_date' => null,
                'credential_id' => null,
                'credential_url' => null,
                'sort_order' => 8,
            ],
            [
                'name' => 'Beginner Back-End Developer',
                'issuing_organization' => 'Dicoding Indonesia',
                'issue_date' => 'Okt 2023',
                'expiration_date' => 'Okt 2026',
                'credential_id' => '07Z6831GJXQR',
                'credential_url' => null,
                'sort_order' => 9,
            ],
            [
                'name' => 'Basic of JavaScript Programming',
                'issuing_organization' => 'Dicoding Academy',
                'issue_date' => 'Okt 2023',
                'expiration_date' => 'Okt 2026',
                'credential_id' => 'EYX4YJ4BOZDL',
                'credential_url' => null,
                'sort_order' => 10,
            ],
            [
                'name' => 'SOLID Programming Principles',
                'issuing_organization' => 'Dicoding Academy',
                'issue_date' => 'Sep 2023',
                'expiration_date' => 'Sep 2026',
                'credential_id' => 'NVP7BQ9YGXR0',
                'credential_url' => null,
                'sort_order' => 11,
            ],
            [
                'name' => 'Beginner Flutter Programming',
                'issuing_organization' => 'Dicoding Academy',
                'issue_date' => 'Sep 2023',
                'expiration_date' => 'Sep 2026',
                'credential_id' => 'GRX52OKR2X0M',
                'credential_url' => null,
                'sort_order' => 12,
            ],
            [
                'name' => 'Basic of C Programming',
                'issuing_organization' => 'Dicoding Academy',
                'issue_date' => 'Sep 2023',
                'expiration_date' => 'Sep 2026',
                'credential_id' => 'EYX4YJ3VJZDL',
                'credential_url' => null,
                'sort_order' => 13,
            ],
            [
                'name' => 'Python Dasar (Gold)',
                'issuing_organization' => 'Skilvul',
                'issue_date' => 'Sep 2023',
                'expiration_date' => 'Sep 2025',
                'credential_id' => '64f181a2a0dca72fe3d7e9b2',
                'credential_url' => null,
                'sort_order' => 14,
            ],
            [
                'name' => 'JavaScript Intermediate',
                'issuing_organization' => 'Skilvul',
                'issue_date' => 'Sep 2023',
                'expiration_date' => 'Sep 2025',
                'credential_id' => '64f83a69c9e1de4f447e40fb',
                'credential_url' => null,
                'sort_order' => 15,
            ],
            [
                'name' => 'Web Development Pemula - Special Challenge (Gold)',
                'issuing_organization' => 'Skilvul',
                'issue_date' => 'Sep 2023',
                'expiration_date' => 'Sep 2025',
                'credential_id' => '64f33ee93537650892089f51',
                'credential_url' => null,
                'sort_order' => 16,
            ],
            [
                'name' => 'Beginner Web Development',
                'issuing_organization' => 'Skilvul',
                'issue_date' => 'Sep 2023',
                'expiration_date' => 'Sep 2025',
                'credential_id' => '64f57fe2353765089208b28c',
                'credential_url' => null,
                'sort_order' => 17,
            ],
            [
                'name' => 'Basic JavaScript',
                'issuing_organization' => 'Skilvul',
                'issue_date' => 'Sep 2023',
                'expiration_date' => 'Sep 2025',
                'credential_id' => '64f1d6ae3537650892088595',
                'credential_url' => null,
                'sort_order' => 18,
            ],
            [
                'name' => 'Basic CSS',
                'issuing_organization' => 'Skilvul',
                'issue_date' => 'Sep 2023',
                'expiration_date' => 'Sep 2025',
                'credential_id' => '64f18b428f03430d2b9c6423',
                'credential_url' => null,
                'sort_order' => 19,
            ],
            [
                'name' => 'Basic HTML',
                'issuing_organization' => 'Skilvul',
                'issue_date' => 'Sep 2023',
                'expiration_date' => 'Sep 2025',
                'credential_id' => '64f187488f03430d2b9c63e7',
                'credential_url' => null,
                'sort_order' => 20,
            ],
            [
                'name' => 'Basic of Dart Programming',
                'issuing_organization' => 'Dicoding Academy',
                'issue_date' => 'Jun 2022',
                'expiration_date' => 'Jun 2025',
                'credential_id' => 'EYX42VQGWZDL',
                'credential_url' => null,
                'sort_order' => 21,
            ],
            [
                'name' => 'CCNA: Switching, Routing, and Wireless Essentials',
                'issuing_organization' => 'Cisco Networking Academy',
                'issue_date' => 'Jun 2022',
                'expiration_date' => null,
                'credential_id' => null,
                'credential_url' => null,
                'sort_order' => 22,
            ],
            [
                'name' => 'CCNA: Introduction to Networks',
                'issuing_organization' => 'Cisco Networking Academy',
                'issue_date' => 'Jun 2022',
                'expiration_date' => null,
                'credential_id' => null,
                'credential_url' => null,
                'sort_order' => 23,
            ],
            [
                'name' => 'Cloud Practitioner Essentials',
                'issuing_organization' => 'Dicoding Academy',
                'issue_date' => 'Apr 2021',
                'expiration_date' => 'Apr 2024',
                'credential_id' => 'JMZVM0R2RZN9',
                'credential_url' => null,
                'sort_order' => 24,
            ],
            [
                'name' => 'Certificate of excellence : Pengenalan CCNA',
                'issuing_organization' => 'Skill Academy by Ruangguru',
                'issue_date' => 'Okt 2020',
                'expiration_date' => null,
                'credential_id' => 'L1666UTAISY89Z',
                'credential_url' => null,
                'sort_order' => 25,
            ],
            [
                'name' => 'Basic of Web Programming',
                'issuing_organization' => 'Dicoding Indonesia',
                'issue_date' => 'Sep 2020',
                'expiration_date' => 'Sep 2023',
                'credential_id' => 'GRX5GGQD3X0M',
                'credential_url' => null,
                'sort_order' => 26,
            ],
            [
                'name' => 'Certificate of Completion : Practical Web Development',
                'issuing_organization' => 'Udemy',
                'issue_date' => 'Sep 2020',
                'expiration_date' => null,
                'credential_id' => 'UC-bc901c1a-cdf0-449c-975d-1751ae7d8106',
                'credential_url' => null,
                'sort_order' => 27,
            ],
            [
                'name' => 'Certificate of Completion : Mikrotik',
                'issuing_organization' => 'Udemy',
                'issue_date' => 'Sep 2020',
                'expiration_date' => null,
                'credential_id' => 'UC-4e5848c4-b32b-48eb-8dc0-d72afab04f47',
                'credential_url' => null,
                'sort_order' => 28,
            ],
        ];

        foreach ($certificates as $cert) {
            \App\Models\Certificate::create($cert);
        }
    }
}
